name: hi world of sneha

on:
  push:
    branches: [master]

jobs:
  greetings:  
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello $USER"
        
      - name: say hello to user
        run: echo "hello dosto"
        
